[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[env]
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]
