[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.setup]
nixPkgs = ["nodejs", "npm"]
